# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


source 'https://github.com/CocoaPods/Specs.git'
#platform :ios, '10.0'
use_frameworks!

target 'ARKitDraw' do
    pod 'Alamofire', '~> 4.7'
end
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for ARKitDraw

#end
